### ISSUE TITLE
Error occurs when using multithreads

### ISSUE THREAD

**Issue by huangnengCSU** [samtools/samtools#1293]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.10
Using htslib 1.10

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
Ubuntu 18.04
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
user@ubuntu: samtools view -bS -@ 40 read_to_contig.sam -o read_to_contig.bam
[main_samview] truncated file.
Segmentation fault (core dumped)
user@ubuntu: samtools view -bS -@ 1 read_to_contig.sam -o read_to_contig.bam
success.

**Comment by valeriuo** [comment]
Couldn't reproduce the behaviour with the latest released versions (samtools ~ 1.10/HTSlib ~ 1.10.2). Any chance we can have an anonymised subset of your data that triggers this error?

**Comment by daviesrob** [comment]
Do you have a copy of `gdb` installed?  If so, you could try:
```
gdb -args samtools view -b -@ 40 read_to_contig.sam -o read_to_contig.bam
```
The gdb command `run` will start the program.  If it crashes, you can use `bt` to get a backtrace, which you can cut and paste here.  When you've finished, use `quit` to exit gdb.

**Comment by huangnengCSU** [comment]
@valeriuo I have replace samtools v1.10 by v1.9, and it didn't report problems any more.

**Comment by valeriuo** [comment]
We would still need to understand what happened. 1.10 introduced a new multi-threading code for SAM files. As it looks now, this code might be the culprit, but if you can run your command under `gdb` or provide us with data that induces the error, it would significantly reduce the investigation time.

**Comment by huangnengCSU** [comment]
The gdb info is following:
`
(gdb) run
Starting program: /home/user/tools/samtools-1.10/bin/samtools view -bS -@ 40 filter_read_to_contig.sam -o filter_read_to_contig.bam
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff17fc700 (LWP 44201)]
[New Thread 0x7ffff0ffb700 (LWP 44202)]
[New Thread 0x7ffff07fa700 (LWP 44203)]
[New Thread 0x7fffefff9700 (LWP 44204)]
[New Thread 0x7fffef7f8700 (LWP 44205)]
[New Thread 0x7fffeeff7700 (LWP 44206)]
[New Thread 0x7fffee7f6700 (LWP 44207)]
[New Thread 0x7fffedff5700 (LWP 44208)]
[New Thread 0x7fffed7f4700 (LWP 44209)]
[New Thread 0x7fffecff3700 (LWP 44210)]
[New Thread 0x7fffec7f2700 (LWP 44211)]
[New Thread 0x7fffebff1700 (LWP 44212)]
[New Thread 0x7fffeb7f0700 (LWP 44213)]
[New Thread 0x7fffeafef700 (LWP 44214)]
[New Thread 0x7fffea7ee700 (LWP 44215)]
[New Thread 0x7fffe9fed700 (LWP 44216)]
[New Thread 0x7fffe97ec700 (LWP 44217)]
[New Thread 0x7fffe8feb700 (LWP 44218)]
[New Thread 0x7fffe87ea700 (LWP 44219)]
[New Thread 0x7fffe7fe9700 (LWP 44220)]
[New Thread 0x7fffe77e8700 (LWP 44221)]
[New Thread 0x7fffe6fe7700 (LWP 44222)]
[New Thread 0x7fffe67e6700 (LWP 44223)]
[New Thread 0x7fffe5fe5700 (LWP 44224)]
[New Thread 0x7fffe57e4700 (LWP 44225)]
[New Thread 0x7fffe4fe3700 (LWP 44226)]
[New Thread 0x7fffe47e2700 (LWP 44227)]
[New Thread 0x7fffe3fe1700 (LWP 44228)]
[New Thread 0x7fffe37e0700 (LWP 44229)]
[New Thread 0x7fffe2fdf700 (LWP 44230)]
[New Thread 0x7fffe27de700 (LWP 44231)]
[New Thread 0x7fffe1fdd700 (LWP 44232)]
[New Thread 0x7fffe17dc700 (LWP 44233)]
[New Thread 0x7fffe0fdb700 (LWP 44234)]
[New Thread 0x7fffe07da700 (LWP 44235)]
[New Thread 0x7fffdffd9700 (LWP 44236)]
[New Thread 0x7fffdf7d8700 (LWP 44237)]
[New Thread 0x7fffdefd7700 (LWP 44238)]
[New Thread 0x7fffde7d6700 (LWP 44239)]
[New Thread 0x7fffddfd5700 (LWP 44240)]
[New Thread 0x7fffdd7d4700 (LWP 44241)]
[New Thread 0x7fffdcfd3700 (LWP 44242)]
[main_samview] truncated file.
munmap_chunk(): invalid pointer

Thread 43 "samtools" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdcfd3700 (LWP 44242)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff674a8b1 in __GI_abort () at abort.c:79
#2  0x00007ffff6793907 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff68c0dfa "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff679a97a in malloc_printerr (str=str@entry=0x7ffff68c2a08 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007ffff67a1f3c in munmap_chunk (p=0x7fffb960c000) at malloc.c:2846
#5  __GI___libc_free (mem=0x7fffb960c010) at malloc.c:3117
#6  0x00005555555eebe8 in cleanup_sp_lines (arg=0x7fffd82de580) at sam.c:2490
#7  0x00005555555ff5eb in hts_tpool_process_reset (q=q@entry=0x5555558d8910, free_results=free_results@entry=0) at thread_pool.c:928
#8  0x00005555555ff726 in hts_tpool_process_destroy (q=0x5555558d8910) at thread_pool.c:406
#9  0x00005555555ef3b3 in sam_dispatcher_read (vp=0x5555558a5390) at sam.c:2657
#10 0x00007ffff7bbd6db in start_thread (arg=0x7fffdcfd3700) at pthread_create.c:463
#11 0x00007ffff682ba3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`

**Comment by jkbonfield** [comment]
I've managed to reproduce similar bugs by deliberately stressing memory and triggering out-of-memory errors.  The results are a bit random, but include the above stack trace sometimes.

Example of stress script:

```
for i in `seq 2000000 -10000 1000000`;do echo $i;bash -c "ulimit -v $i;./test/test_view -@40 /tmp/1m.2.sam | wc -l";done
```

Therefore I suspect your crash could be related.  Have you tried permitting it to use more memory, or reducing the number of threads which will reduce the memory usage?

It's clearly a bug as we should throw an error and shutdown cleanly instead of going bang, but in memory stressed situations we won't be able to just keep going.

**Comment by huangnengCSU** [comment]
@jkbonfield 
Thanks for your valuable response. But I think it may not be the problem of memory. The size of sam file is 3.4Gb and the size of memory is 256Gb. The threads number is been set to 2. But it still has the problem. I replaced the samtools v1.10 by samtools v1.9, the problem did not occur.

**Comment by jkbonfield** [comment]
So this is completely consistent and happens every time?  That's definitely odd.  We can't reproduce it here except for the case when it's already gone wrong (failing memory allocations), and it's also been through multiple thread checking tools.  Note although the system may have 256GB of memory, we've seen some others with memory constrained jobs failing before which was due to system hard memory limits ("ulimit -a" will show them), imposed by a job / batch submission system.

When it dies, do you have any feeling for how far through the process it got?  Is the BAM output file more or less the expected size that you'd see when using 1.9, or significantly smaller?  If it's comparable then it's probably not a memory issue as it's essentially finished already.  Failing with just 2 threads also indicates it's likely not memory related.  Struggling on this!

PS. It's not surprising it doesn't happen with 1.9 as that had no multi-threaded SAM capability at all.

**Comment by jkbonfield** [comment]
Also this line has me wondering:

```
 [main_samview] truncated file.
```

I have detected that some malformed SAM files aren't detected when not multi-threading, but are when using threads.  In that case it was lines ending in tabs which caused a difference.

If you do something like `tail -1 read_to_contig.sam |hd` you should see the final SAM record.  Does it look intact, ending in a newline as expected?

**Comment by daviesrob** [comment]
Whatever is causing the problem happens earlier than the actual crash, so running with address sanitizer might help find it.  Would it be possible to try it?

The easiest way to do this is to configure samtools and htslib in the normal way, and then when you build them use:
```
make CC='gcc -fsanitize=address'
```

That will build a samtools with extra debugging code.  To get sensible traces out of it, it's best to set environment variable `ASAN_OPTIONS` to `allow_addr2line=true` before running the program, for example:

```
ASAN_OPTIONS=allow_addr2line=true samtools view -b -@ 40 read_to_contig.sam -o read_to_contig.bam
```

If it detects anything it will give a fairly lengthy print-out showing where the problem was.

**Comment by jkbonfield** [comment]
Note you can also try `CC='gcc -fsanitize=thread'` too, but not both at once as I recall.

**Comment by jkbonfield** [comment]
I've done some investigations into possible threading errors and found some bugs in handling errors.  These should be fixed in https://github.com/jkbonfield/htslib/tree/SAM_thread

(Note that's htslib rather than Samtools, so you'll need to rebuild both packages.)

Could you please try this branch and let us know if it fixes your problem?  Thanks.

**Comment by huangnengCSU** [comment]
To jkbonfield
I have redownloaded the htslib then rebuild htslib and samtool. The same error still occurred.
Neng

**Comment by jkbonfield** [comment]
Thanks for testing.  Sorry it didn't fix it.

When it dies, do you have any feeling for how far through the process it got? Is the BAM output file more or less the expected size that you'd see when using 1.9, or significantly smaller?

If it dies early on, then this definitely points at an algorithmic or data-specific problem.  Is your data confidential, or could we get access to it for testing some how?

It may be possible to produce some test data for us to experiment with.  Note this may not need the full sequence present (depending on what is triggering the bug); maybe try randomising the sequence and replacing the cigar/rnext/pnext/tlen fields with dummy data, and dropping aux tags too so that any confidential information is removed.  (Maybe read name would need to go too?)   For example:

```
samtools view -h in.sam | perl -lane 'BEGIN{$"="\t";@b=qw/A C G T/};if (/^@/) {print;next} $x=join("", map{$b[int(rand(4))]} split("",$F[9]));$F[5]=length($F[9])."M" if ($F[5] ne "*");$F[6]="*";$F[7]=0;$F[8]=0;print "@F[0..10]"' > out.sam
```

If that SAM file still produces the same problem, then you could judge whether or not there's anything confidential leaked in there.  (Check the header too.)

**Comment by jmarshall** [comment]
@huangnengCSU: What does `samtools --version-only` say for your recently rebuilt samtools? I assume you're building from a git repository, so it'll say something like 1.10-NN-g1234567+htslib-1.10.2-114-g8706c0f?

**Comment by huangnengCSU** [comment]
samtools 1.10
Using htslib 1.10
Copyright (C) 2019 Genome Research Ltd.
1.10+htslib-1.10

**Comment by valeriuo** [comment]
@huangnengCSU that is the same version you were running before.
Please try the following script to get the latest fixes:
```
git clone --branch SAM_thread https://github.com/jkbonfield/htslib.git htslib-test
git clone --branch develop https://github.com/samtools/samtools.git samtools-test
cd htslib-test/
autoconf; autoheader; ./configure; make
cd ../samtools-test/
autoheader; autoconf -Wno-syntax; ./configure --with-htslib=../htslib-test; make
```

You can now run the samtools binary from the current folder (**samtools-test**) with:
`./samtools view -@ 40 read_to_contig.sam -o read_to_contig.bam`

**Comment by huangnengCSU** [comment]
@valeriuo 
I ran the scripts and the error is as follows:


The version of samtools and htslib is:
1.10-89-g90a8ca4+htslib-

**Comment by jkbonfield** [comment]
Just a quick update: I've figured out what I think is the cause of this bug and am working on it.

It's a length of line issue, presumably due to long ONT records.  In theory that shouldn't be an issue, but I've managed to reproduce the bug so clearly there is an issue here.
