### ISSUE TITLE
"Incomplete aux field" error in samtools sort with version 1.11.0 but not in 1.9

### ISSUE THREAD

**Issue by DaGaMs** [samtools/samtools#1472]
I have a version of samtools and htslib compiled with clang and using libdeflate 1.7. When I try to pipe the output of hisat2-3n directly into `samtools sort`, I'm getting this error:

```
[E::sam_parse1] incomplete aux field
samtools sort: truncated file. Aborting
[E::sam_parse1] incomplete aux field
```

I have saved the first few thousand aligned reads [in a sam file for debugging](https://www.dropbox.com/s/jl64dneww4vsl20/out.sam.gz?dl=0).

The weird thing is this:

```
# This FAILS!
samtools sort -@ 2 -o test.bam -O bam out.sam

# This WORKS!
samtools view -b out.sam | samtools sort -@ 2 -o test.bam -O bam
```

Any idea what's going on there?

**Comment by whitwham** [comment]
I tried your test file against the newest 1.13 version of samtools and I got no errors.  

Can you update your samtools/htslib to the current version and try again?

**Comment by jmarshall** [comment]
I believe this is exhibiting the multithreading SAM reading problem that was fixed by samtools/htslib#1149, which is intriguing because the test file does not have CR-LF lines… 🤔

**Comment by daviesrob** [comment]
I can confirm that this was fixed by samtools/htslib#1149.  As well as adding support for CR-LF lines, it also [corrected](https://github.com/samtools/htslib/pull/1149/commits/5bb4b171) the length of the string passed to `sam_parse1()` - the original version incremented `nl` before using it to calculate the length so one extra character was included.  This didn't appear to be a problem for reads with aux tags, but did cause an error on reads that ended with the QUAL string, as in the example file.

Upgrading to the latest release will fix the problem; or you could work around it in `1.11` by not using the `-@` option.

**Comment by DaGaMs** [comment]
Hmm, I just recompiled samtools and htslib to version 1.13, and I still get the same issue:

```
$ samtools --version
samtools 1.13
Using htslib 1.13
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             gcc
    CPPFLAGS:       -I/opt/apps/pkg/apps/libdeflate/1.7/gcc-4.8.5/include -I/opt/apps/pkg/compilers/clang/11.0.1/gcc-8.3.0+zlib-1.2.11+python3-3.8.1+libxml-2.9.10/include
    CFLAGS:         -Wall -g -O2
    LDFLAGS:        -L/opt/apps/pkg/apps/libdeflate/1.7/gcc-4.8.5/lib -L/opt/apps/pkg/compilers/clang/11.0.1/gcc-8.3.0+zlib-1.2.11+python3-3.8.1+libxml-2.9.10/lib
    HTSDIR:         
    LIBS:           
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure plugins=no libcurl=yes S3=yes GCS=yes libdeflate=yes lzma=yes bzip2=yes htscodecs=1.1.1
    CC:             gcc
    CPPFLAGS:       -I/opt/apps/pkg/apps/libdeflate/1.7/gcc-4.8.5/include -I/opt/apps/pkg/compilers/clang/11.0.1/gcc-8.3.0+zlib-1.2.11+python3-3.8.1+libxml-2.9.10/include
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -L/opt/apps/pkg/apps/libdeflate/1.7/gcc-4.8.5/lib -L/opt/apps/pkg/compilers/clang/11.0.1/gcc-8.3.0+zlib-1.2.11+python3-3.8.1+libxml-2.9.10/lib -fvisibility=hidden 

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    S3 Multipart Upload:         s3w, s3w+https, s3w+http
    Amazon S3:   s3+https, s3+http, s3
    Google Cloud Storage:        gs+http, gs+https, gs
    libcurl:     imaps, pop3, http, smb, gopher, ftps, imap, smtp, smtps, rtsp, ftp, telnet, smbs, https, tftp, pop3s, dict
    crypt4gh-needed:     crypt4gh
    mem:         mem
```

```
[E::aux_parse] invalid aux tag id
samtools sort: truncated file. Aborting
[E::aux_parse] invalid aux tag id
```

**Comment by jkbonfield** [comment]
Does it fail for you on the small test set you uploaded, or only on your main file?

I cannot reproduce this problem with your test data. I'm trying various thread sanitizers right now to see if they spot anything.

**Comment by DaGaMs** [comment]
Sorry, bad bug report 🙈 It does indeed _not_ fail on the test data I previously sent. Now it's failing at a different place, and I do get the same issue in older versions of samtools. There is probably something wrong with hisat2's output, but I'm not sure what the issue is. The read it's dying on is this:

```
A00711:92:HMH3WDSXX:1:1101:8250:1000    69      chrUn_KN707896v1_decoy  4657    0       *       =       4657    0       TCCATTCTATTCGGGTTAATTCCATTCCATTCCATTCCATTCCATTCCATTCTATTCCATTCCATTGCAATCGAGTTGAATCAATTGCATTTCATTCCATTCCATTCCATTCCATTCTGGAAGTATCCAGTCCATTGCATTCCATTCCAT       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,F,FF,FF,FF:,,F:FF:,F:FFFFF,FFFFFFFFFF:FFFFFFFF,:F:FF:,F:FF,F,F,:,FF:FF,,,::F,,:,FF::F               RG:Z:ID:92:HMH3WDSXX:1
```

I've made a new test case, find the sam file [here](https://www.dropbox.com/s/0aliu4taxvjw1a5/out-2.sam.gz?dl=0)

**Comment by daviesrob** [comment]
There are two tabs in the line that gives the error, between the quality values and the aux tags:
```
$ zcat /tmp/out-2.sam.gz | head -n 3449 | tail -n 1 | perl -pe 's/\t/ <tab> /g'
A00711:92:HMH3WDSXX:1:1101:8250:1000 <tab> 69 <tab> chrUn_KN707896v1_decoy <tab> 4657 <tab> 0 <tab> * <tab> = <tab> 4657 <tab> 0 <tab> TCCATTCTATTCGGGTTAATTCCATTCCATTCCATTCCATTCCATTCCATTCTATTCCATTCCATTGCAATCGAGTTGAATCAATTGCATTTCATTCCATTCCATTCCATTCCATTCTGGAAGTATCCAGTCCATTGCATTCCATTCCAT <tab> FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,F,FF,FF,FF:,,F:FF:,F:FFFFF,FFFFFFFFFF:FFFFFFFF,:F:FF:,F:FF,F,F,:,FF:FF,,,::F,,:,FF::F <tab>  <tab> RG:Z:ID:92:HMH3WDSXX:1
```

You can fix up the file with a bit of perl hackery:
```
$ zcat /tmp/out-2.sam.gz | ./samtools view -c -
[E::aux_parse] invalid aux tag id
[W::sam_read1_sam] Parse error at line 3449
samtools view: error reading file "-"

$ zcat /tmp/out-2.sam.gz | perl -pe 's/\t\t/\t/' | ./samtools view -c -
74
```
