### ISSUE TITLE
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai

### ISSUE THREAD

**Issue by rl4940** [samtools/samtools#2057]
samtools 1.19.2
Using htslib 1.19.1
Linux 3.10.0-1160.118.1.el7.x86_64

Hi my question is that I receive this when doing sniffles2:
```
[W::hts_idx_load3] The index file is older than the data file: alignment.sorted.bam.bai
```
And my code for minimap2/samtools is down blow:
```
minimap2 -ax map-ont --secondary=no --MD -t 18 $ref $fastqgz_all\
|samtools sort -O BAM --write-index -o alignment.sorted.bam##idx##alignment.sorted.bam.bai -
```
I do not know what's going on.
Thanks for your help!
Li

**Comment by daviesrob** [comment]
This problem should be fixed in htslib 1.20 (included with the [samtools 1.20 release](https://github.com/samtools/samtools/releases)).  Before that, the index and output files could be closed in the wrong order leading to the misleading warning that you got.

To fix, you can either:
* Upgrade to version 1.20 (best, you fix other bugs too)
* Index the output file separately using `samtools index`
* Use [touch](https://linux.die.net/man/1/touch) on the index file so the timestamp is later than the one on the sort output
* Or just ignore the warning as it should be harmless

**Comment by mweberr** [comment]
The problem remains with htslib1.21
I got the same issue running following lines of code:
 samtools view -hb -F 4 -q 2 test.sam | samtools sort -o test_sorted.sam && \
samtools index test_sorted.sam
